package com.bplow.deep.stock.domain;

import com.bplow.deep.base.pagination.PageInfo;

public class SkDaySwrich extends PageInfo{
	
    /**  */
    private static final long serialVersionUID = -5650382747944114821L;

    private String id;

    private String yesterDay;

    private String today;

    private String tommory;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getYesterDay() {
        return yesterDay;
    }

    public void setYesterDay(String yesterDay) {
        this.yesterDay = yesterDay == null ? null : yesterDay.trim();
    }

    public String getToday() {
        return today;
    }

    public void setToday(String today) {
        this.today = today == null ? null : today.trim();
    }

    public String getTommory() {
        return tommory;
    }

    public void setTommory(String tommory) {
        this.tommory = tommory == null ? null : tommory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_day_swrich
     *
     * @mbggenerated Sun Mar 05 23:29:04 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SkDaySwrich other = (SkDaySwrich) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getYesterDay() == null ? other.getYesterDay() == null : this.getYesterDay().equals(other.getYesterDay()))
            && (this.getToday() == null ? other.getToday() == null : this.getToday().equals(other.getToday()))
            && (this.getTommory() == null ? other.getTommory() == null : this.getTommory().equals(other.getTommory()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_day_swrich
     *
     * @mbggenerated Sun Mar 05 23:29:04 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getYesterDay() == null) ? 0 : getYesterDay().hashCode());
        result = prime * result + ((getToday() == null) ? 0 : getToday().hashCode());
        result = prime * result + ((getTommory() == null) ? 0 : getTommory().hashCode());
        return result;
    }
}