package com.bplow.deep.stock.domain;

import java.util.Date;

import com.bplow.deep.base.pagination.PageInfo;

public class SkSendSmsLog extends PageInfo{
    /**  */
    private static final long serialVersionUID = 2319825560809292827L;

    private String smsId;

    private String sendMobile;

    private String sendCnt;

    private String parament;

    private Date gmtCreate;

    private String status;

    public String getSmsId() {
        return smsId;
    }

    public void setSmsId(String smsId) {
        this.smsId = smsId == null ? null : smsId.trim();
    }

    public String getSendMobile() {
        return sendMobile;
    }

    public void setSendMobile(String sendMobile) {
        this.sendMobile = sendMobile == null ? null : sendMobile.trim();
    }

    public String getSendCnt() {
        return sendCnt;
    }

    public void setSendCnt(String sendCnt) {
        this.sendCnt = sendCnt == null ? null : sendCnt.trim();
    }

    public String getParament() {
        return parament;
    }

    public void setParament(String parament) {
        this.parament = parament == null ? null : parament.trim();
    }

    public Date getGmtCreate() {
        return gmtCreate;
    }

    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_send_sms_log
     *
     * @mbggenerated Sat Feb 25 16:50:55 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        SkSendSmsLog other = (SkSendSmsLog) that;
        return (this.getSmsId() == null ? other.getSmsId() == null : this.getSmsId().equals(other.getSmsId()))
            && (this.getSendMobile() == null ? other.getSendMobile() == null : this.getSendMobile().equals(other.getSendMobile()))
            && (this.getSendCnt() == null ? other.getSendCnt() == null : this.getSendCnt().equals(other.getSendCnt()))
            && (this.getParament() == null ? other.getParament() == null : this.getParament().equals(other.getParament()))
            && (this.getGmtCreate() == null ? other.getGmtCreate() == null : this.getGmtCreate().equals(other.getGmtCreate()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sk_send_sms_log
     *
     * @mbggenerated Sat Feb 25 16:50:55 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSmsId() == null) ? 0 : getSmsId().hashCode());
        result = prime * result + ((getSendMobile() == null) ? 0 : getSendMobile().hashCode());
        result = prime * result + ((getSendCnt() == null) ? 0 : getSendCnt().hashCode());
        result = prime * result + ((getParament() == null) ? 0 : getParament().hashCode());
        result = prime * result + ((getGmtCreate() == null) ? 0 : getGmtCreate().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        return result;
    }
}