CREATE TABLE `sk_transaction_record` (
	`id` VARCHAR(32) NOT NULL,
	`stock_id` VARCHAR(6) NULL DEFAULT NULL,
	`stock_name` VARCHAR(32) NULL DEFAULT NULL,
	`amount` BIGINT(20) NULL DEFAULT NULL,
	`price` DOUBLE NULL DEFAULT NULL,
	`transaction_type` VARCHAR(1) NULL DEFAULT NULL,
	`gmt_create` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`gmt_modify` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;


CREATE TABLE `sk_warehouse_positon` (
	`stock_id` VARCHAR(6) NOT NULL,
	`stock_name` VARCHAR(32) NULL DEFAULT NULL,
	`amount` BIGINT(20) NULL DEFAULT NULL,
	`yester_price` DOUBLE NULL DEFAULT NULL,
	`today_price` DOUBLE NULL DEFAULT NULL,
	`market_value` DOUBLE NULL DEFAULT NULL,
	`sort_by` BIGINT(20) NULL DEFAULT NULL,
	`gmt_create` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`gmt_modify` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
	PRIMARY KEY (`stock_id`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
;